apiVersion: v2
name: rancher-backup-crd
appVersion: 999
version: 999
description: Installs the CRDs for rancher-backup.
type: application
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cattle-resources-system
  catalog.cattle.io/release-name: rancher-backup-crd
  catalog.cattle.io/rancher-version: "<2.5.99-0"
